### ISSUE TITLE
Initial Release Roadmap

### ISSUE THREAD

**Issue by BruceCodesGithub** [Pycord-Development/guide#35]
## Getting Started

- [x] Creating your first bot
- [x] More Features
  - [x] Design (#40)
    - [x] Embeds
      > Needs example discord components
    - [x] Markdown in Messages
  - [x] Events
  - [x] wait_for
- [x] Rules & Common Practices
  > May need partial rewriting
- [x] Hosting your bot

### ✅ Commands
- [x] Slash Commands
- [x] Context Menus
- [x] Localization (#59)
~~Cogs with Application Commands (see #75)~~ moved to the Popular Topics section

### ✅ UI Components
- [x] Button
- [x] Dropdowns
- [x] Text Modals

### ✅ Commands

- [x] Prefixed Commands
- [x] Command Groups
- [x] Help Command
- [x] Cogs

### ✅ Tasks
- [x] Getting Started with `ext.tasks` (#31)

### ✅ Pages (guide progress on `ext.pages` might be halted for now)
- [x] Getting Started with `ext.pages`

### ✅ Bridge
- [x] Getting Started with `ext.bridge`

## Popular Topics

- [ ] Webhooks
- [x] Sharding
- [x] Sublcassing Bot
- [x] Intents
- [x] Threads
- [x] Cogs (see #112)

## Voice

NOTE: might be ignored, for the initial release

- [x] Receiving Voice Samples
- [ ] Playing Audio
- [ ] Creating Voice Commands

## ✅ More
- [x] Installing Git
- [x] Community Resources
- [x] Contributing to the guide
- [x] Virtual Enviorments (#65)

# Low Priority
Unless the team decides to create the page or a PR for it is made these aren’t required for release

- Creating Voice Commands
- Playing Audio
- Anything else not on the list, mostly to remove "feature creep" from the list

**Comment by BruceCodesGithub** [comment]
`ext.pages`, Text Modals rewrite under development by @krittick.

**Comment by ConchDev** [comment]
More Features is currently under Getting Started. Might want to be moved somewhere else.

**Comment by ConchDev** [comment]
Hey I can't commit

**Comment by BruceCodesGithub** [comment]
> More Features is currently under Getting Started. Might want to be moved somewhere else.

The page will contain some basic bot features. Changing the name of the page might be better.

**Comment by VincentRPS** [comment]
> Hey I can't commit

(Resolved on discord) branch protection rules.

**Comment by BruceCodesGithub** [comment]
Pages not under known development by any team member:
- Popular Topics/ Webhooks
- Voice/ Playing Audio
- Voice/ Creating Voice Commands

**Comment by BruceCodesGithub** [comment]
The voice pages names might change in the future.

**Comment by BruceCodesGithub** [comment]
#40

**Comment by EmreTech** [comment]
Localization guide in progress via #59.

**Comment by BruceCodesGithub** [comment]
Dropdowns and Modal Dialogs Guide rewritten (c2a7db8eeb97a3983f968577b4673fb9cfafe79d)
